# SVD 
Rajkumar Verma

In [83]:
import numpy as np

In [84]:
A = np.array([[1, 0, 1],
              [-1, 1, 0]])

# 2. Eigen Value and Eigen Vector

In [85]:
# A@ eigen_vector = eigen_value @ eigen_vector
AT_A = A.transpose()@A
Veigenvalues, Veigenvector = np.linalg.eig(AT_A)

In [86]:
AT_A

array([[ 2, -1,  1],
       [-1,  1,  0],
       [ 1,  0,  1]])

In [87]:
Veigenvalues

array([ 3.00000000e+00, -2.22044605e-16,  1.00000000e+00])

In [88]:
print(f"eigen vec of V = {Veigenvector}")

array([[ 8.16496581e-01, -5.77350269e-01, -1.57009246e-16],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01],
       [ 4.08248290e-01,  5.77350269e-01,  7.07106781e-01]])

In [89]:
r = np.linalg.matrix_rank(A)
r

2

In [90]:
Veigenvalues

array([ 3.00000000e+00, -2.22044605e-16,  1.00000000e+00])

In [91]:
Veigenvector

array([[ 8.16496581e-01, -5.77350269e-01, -1.57009246e-16],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01],
       [ 4.08248290e-01,  5.77350269e-01,  7.07106781e-01]])

In [96]:
D = np.zeros(A.shape)
D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
# singular value decomposition SVD
U, S, VT = np.linalg.svd(A)

In [100]:
for i in range(r):
    D[i,i] = S[i]
D

array([[1.73205081, 0.        , 0.        ],
       [0.        , 1.        , 0.        ]])

In [99]:
print(f"singular values: S = {S}")

singular values: S = [1.73205081 1.        ]


In [105]:
print(f"U : \n {U} \n S:\n {S} \n VT :\n {VT}")

U : 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]] 
 S:
 [1.73205081 1.        ] 
 VT :
 [[-8.16496581e-01  4.08248290e-01 -4.08248290e-01]
 [-1.19879883e-16  7.07106781e-01  7.07106781e-01]
 [-5.77350269e-01 -5.77350269e-01  5.77350269e-01]]


In [106]:
print(U@D@VT)

[[ 1.00000000e+00 -1.21168839e-16  1.00000000e+00]
 [-1.00000000e+00  1.00000000e+00  3.36389635e-16]]
